config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'

  root 'homepage#index'

  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
    validate :event_cannot_be_in_the_past
    validate :start_before_end

    def start_time
        self.startDay
    end

    def event_cannot_be_in_the_past
        hour = Time.now.strftime('%k').to_i
        min = Time.now.strftime('%M').to_i
        if startDay < Date.today
            errors.add(:Event, "can not be in the past")
        elsif startDay == Date.today
            if startTime.strftime('%k').to_i < hour
                    errors.add(:Event, "can not be in the past")
            elsif startTime.strftime('%k').to_i == hour
                if startTime.strftime('%M').to_i < min
                    errors.add(:Event, "can not be in the past")
                end
            end
        end
    end

    def start_before_end
        if endDay < startDay
            errors.add(:Event, "end can not be before start")
        elsif endDay == startDay
            if endTime.strftime('%k').to_i < startTime.strftime('%k').to_i
                errors.add(:Event, "end can not be before start")
            elsif endTime.strftime('%k').to_i == startTime.strftime('%k').to_i
                if endTime.strftime('%M').to_i < startTime.strftime('%M').to_i
                    errors.add(:Event, "end can not be before start")
                end
            end
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def new
		@event = Event.new
	end

	def index
        # logic to pick the events based on what day or if all events was selected
		@events = Event.all
        if params[:show_all]
            @events
        else
            @result = []
            @events.each do |event|
                if event.startDay.strftime('%m/%d/%y') == params[:date]
                    @result.push(event)
                end
            end
            @events = @result
        end

        # passing params to create to be able to return to correct one
        if params[:show_all]
            @state = 'true'
        elsif params[:date] != nil
            @state = params[:date]
        else
            @state = ''
        end

        # variable to allow next day and previous day to be done and return to current month
        if params[:date] != nil
            @day = params[:date][3,2]
            @month = params[:date][0,2]
            @year = params[:date][6,2]
            @year = (2000 + @year.to_i).to_s
            @date = @year + "/" + @month + "/" + @day
            @date = @date.to_date
            @nextDay = (@date + 1).strftime('%m/%d/%y')
            @prevDay = (@date - 1).strftime('%m/%d/%y')
        end
	end

	def edit
		@event = Event.find(params[:id])
	end

	def show
		@event = Event.find(params[:id])
	end

	def create
		@event = Event.new(event_params)
		if @event.save
			redirect_to @event
		else
			render 'new'
		end
	end

	def update
		@event = Event.find(params[:id])

		if @event.update(event_params)
			redirect_to @event
		else
			render 'edit'
		end
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy

		redirect_to events_path
	end

	private
		def event_params
			params.require(:event).permit(:eventName, :location, :startTime, :startDay, :endTime, :endDay, :description, :facebookLink)
		end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
      @events = Event.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
    <% # If any errors, show all of them here %>
	<% if @event.errors.any? %>
    	<div id="error_explanation">
      	<h2>
            Whoops! Something wrong with your event.
      	</h2>
      	<p>
        	<% @event.errors.full_messages.each do |msg| %>
          		<li><%= msg %></li>
        	<% end %>
      	</p>
    	</div>
  	<% end %>

<div class = "formall">
  <div class = "formgroup">
    <span class = "formlabel"><%= f.label :'Event Name' %></span><br>
    <span class = "forminput"><%= f.text_field :eventName, :required => true, :class => "forminput" %></span>
  </div>

  <div class = "formgroup">
    <span class = "formlabel"><%= f.label :Location %></span><br>
    <span class = "forminput"><%= f.text_field :location, :required => true, :class => "forminput" %></span>
  </div>

  <div class = "formgroup">
	<span class = "formlabel"><%= f.label :'Event Start' %></span><br>
	<span class = "forminput"><%= f.time_select :startTime, :default => {:hour => (Time.now.strftime("%k").to_i + 1), :minute => Time.now.strftime("%M")}, :ampm => true, :minute_step => 15 %></span>
	&emsp;
	<span class = "forminput"><%= f.date_select :startDay, :order => [:month, :day, :year], :class => "forminput" %></span>
  </div>

  <div class = "formgroup">
	<span class = "formlabel"><%= f.label :'Event End' %></span><br>
	<span class = "forminput"><%= f.time_select :endTime, :default => {:hour => (Time.now.strftime("%k").to_i + 1), :minute => Time.now.strftime("%M")}, :ampm => true, :minute_step => 15 %></span>
	&emsp;
	<span class = "forminput"><%= f.date_select :endDay, :order => [:month, :day, :year], :class => "forminput" %></span>
  </div>

  <div class = "formgroup">
    <span class = "formlabel"><%= f.label :Description %></span><br>
    <span class = "forminput"><%= f.text_area :description, :required => true, :class => "forminput"  %></span>
  </div>

  <div class = "formgroup">
    <span class = "formlabel"><%= f.label :'Facebook Link' %></span><br>
    <span class = "forminput"><%= f.text_field( :facebookLink, :class => "forminput" ) %></span>
  </div>

  <div class = "formgroup">
    <%= f.submit :class => "submitbutton" %>
  </div>

 </div>



<% end %>

app/views/events/edit.html.erb
<div id = "header">

    <h1><%= link_to 'WesEvents', controller: 'homepage' %></h1>
    <div id = "navbar">
        <button class = "hollowbutton"> <%= link_to 'All Events', controller: 'events', :show_all => true %> </button>
        <button class = "createbutton"> <%= link_to 'Create New Event', new_event_path(:redirect_to => @state) %></button>
    </div>

</div>

<div id = "titlebar">

    <button class = "hollowbutton">
        <%= link_to '<', events_path(:date => @event.startDay.strftime('%m/%d/%y')) %>
    </button>
    <h2>UPDATE EVENT</h2>
    <button class = "dummy">></button>

</div>

<%= render 'form' %>

app/views/events/index.html.erb
<div id = "header">

    <h1><%= link_to 'WesEvents', controller: 'homepage' %></h1>
    <div id = "navbar">
        <button class = "hollowbutton"> <%= link_to 'All Events', controller: 'events', :show_all => true %> </button>
        <button class = "createbutton"> <%= link_to 'Create New Event', new_event_path(:redirect_to => @state) %></button>
    </div>

</div>

<div id = "titlebar">

    <button class = "hollowbutton"><%= link_to "<", controller: 'homepage', :start_date => @date %></button>
    <h2>EVENTS LISTING</h2>
    <button class = "dummy">></button>

</div>



<div id = "eventlist">
    <% if @events != [] %>
        <% # Header whether showing all or just on specific date %>
        <% if !(params[:show_all] == 'true') %>
            <div class = "dayswitch">
                <button class = "dayswitchbutton"><%= link_to 'Previous Day', events_path(:date => @prevDay) %> </button>
                <h3>Events on <%= params[:date] %></h3>
                <button class = "dayswitchbutton"><%= link_to 'Next day', events_path(:date => @nextDay) %> </button>
            </div>
        <% else %>
            <h3>All Events</h3>
        <% end %>
        <table>
          <tr>
            <th width = '150'>Event</th>
            <th width = '150'>Location</th>
            <th width = '150'>Event Start</th>
            <th width = '150'>Event End</th>
            <th width = '150'>Description</th>
            <th width = '150'>Event Link</th>
            <th colspan='3' />
          </tr>
          <% @events.each do |event| %>
            <tr>
                <td id = "listname"><%= event.eventName %></td>
                <td><%= event.location %></td>
                <td><%= event.startTime.strftime('%I:%M %p') %><!--<br><%= event.startDay.strftime('%m/%d/%y') %> --></td>
                <td><%= event.endTime.strftime('%I:%M %p') %><!--<br><%= event.endDay.strftime('%m/%d/%y') %> --></td>
                <td><%= event.description %></td>
                <% if event.facebookLink == "" %>
                    <td id = "listlink"><a href = '<%= event.facebookLink %>' target = '_blank'>Go To Event Page</a></td>
                <% elsif %>
                    <td></td>
                <% end %>
              <td><button class = "listbutton"><%= link_to 'Show', event_path(event) %></button></td>
              <td><button class = "listbutton"><%= link_to 'Edit', edit_event_path(event)%></button></td>
              <td><button class = "listbutton"><%= link_to 'Delete', event_path(event), method: :delete, data: {confirm: 'Are you sure?' } %></button></td>
            </tr>
          <% end %>
        </table>
    <% else %>
        <div class = "dayswitch">
            <button class = "dayswitchbutton"><%= link_to 'Previous Day', events_path(:date => @prevDay) %> </button>
            <h3>Events on <%= params[:date] %></h3>
            <button class = "dayswitchbutton"><%= link_to 'Next day', events_path(:date => @nextDay) %> </button>
        </div>
        <p> No Events to Show! </p>
    <% end %>

</div>

app/views/events/new.html.erb
<div id = "header">

    <h1><%= link_to 'WesEvents', controller: 'homepage' %></h1>
    <div id = "navbar">
        <button class = "hollowbutton"> <%= link_to 'All Events', controller: 'events', :show_all => true %> </button>
        <button class = "createbutton"> <%= link_to 'Create New Event', new_event_path(:redirect_to => @state) %></button>
    </div>

</div>

<div id = "titlebar">

    <button class = "hollowbutton">
        <% if params[:redirect_to] == 'homepage' %>
            <%= link_to '<', controller: 'homepage' %>
        <% elsif params[:redirect_to] == 'true' || params[:redirect_to] == '' %>
            <%= link_to '<', controller: 'events', :show_all => params[:redirect_to] %>
        <% else %>
            <%= link_to '<', controller: 'events', :date => params[:redirect_to] %>
        <% end %>
    </button>
    <h2>NEW EVENT</h2>
    <button class = "dummy">></button>

</div>

<%= render 'form' %>

app/views/events/show.html.erb
<div id = "header">

    <h1><%= link_to 'WesEvents', controller: 'homepage' %></h1>
    <div id = "navbar">
        <button class = "hollowbutton"> <%= link_to 'All Events', controller: 'events', :show_all => true %> </button>
        <button class = "createbutton"> <%= link_to 'Create New Event', new_event_path(:redirect_to => 'homepage') %></button>
    </div>

</div>

<div id = "titlebar">

    <button class = "hollowbutton">
        <%= link_to '<', events_path(:date => @event.startDay.strftime('%m/%d/%y')) %>
    </button>
    <h2><%= @event.eventName %></h2>
    <button class = "dummy">></button>

</div>


<div id = "showlist">

    <h4>
      <span class = "showlabel">Location:</span>
      <%= @event.location %>
    </h4>

    <h4>
      <span class = "showlabel">Event Start:</span>
      <%= @event.startTime.strftime('%I:%M:%S %p') %>
      <%= @event.startDay.strftime('%m/%d/%y') %>
    </h4>

    <h4>
        <span class = "showlabel">Event End:</span>
      <%= @event.endTime.strftime('%I:%M:%S %p') %>
      <%= @event.endDay.strftime('%m/%d/%y') %>
    </h4>

    <h4>
        <span class = "showlabel">Description:</span>
      <%= @event.description %>
    </h4>
    <% if @event.facebookLink != "" %>
        <h4>
            <span class = "showlabel"> Event Link:</span>
            <a href = '<%= @event.facebookLink %>' target = '_blank'><%= @event.facebookLink %><a/>
        </h4>
    <% end %>

    <button id = "showedit" class = "createbutton"><%= link_to 'Go to calendar', :controller=>"homepage", :start_date => @event.startDay %></button>
    <button id = "showedit" class = "hollowbutton"><%= link_to 'Edit', edit_event_path(@event) %></button>


</div>

app/views/homepage/index.html.erb
<div id = "header">

    <h1><%= link_to 'WesEvents', controller: 'homepage' %></h1>
    <div id = "navbar">
        <button class = "hollowbutton"> <%= link_to 'All Events', controller: 'events', :show_all => true %> </button>
        <button class = "createbutton"> <%= link_to 'Create New Event', new_event_path(:redirect_to => 'homepage') %></button>
    </div>

</div>

<div id = "calendar">

    <% # Renders the month calendar %>
    <%= month_calendar events: @events do |date, events| %>
        <% @month = date.strftime('%m') %>
        <% unless params[:start_date].nil? %>
                <div class = "calendardate">
                    <%= link_to '' + date.strftime('%d') + '', events_path(:date => date.strftime('%m/%d/%y')) %>
                </div>
                <% events.each do |event| %>
                    <% # Display event if one on that day %>
                    <div class = "calendarevent">
                        <%= link_to event.eventName, event %>
                    </div>
                <% end %>
        <% else %>
                <div class = "calendardate">
                    <%= link_to '' + date.strftime('%d') + '', events_path(:date => date.strftime('%m/%d/%y')) %>
                </div>
                <% events.each do |event| %>
                    <% # Display event if one on that day %>
                    <div class = "calendarevent">
                        <%= link_to event.eventName, event %>
                    </div>
                <% end %>
            <% end %>
    <% end %>
    <% # Show return to current month if not on current month %>
    <!-- <% unless params[:start_date].nil? %>
        <% unless Time.now.strftime('%m') == params[:start_date][5,2] %>
            <p> <%= link_to 'Return to Current Month', controller: 'homepage' %> </p>
        <% end %>
    <% else %>
        <% unless @month == Time.now.strftime('%m') %>
            <p> <%= link_to 'Return to Current Month', controller: 'homepage' %> </p>
        <% end %>
    <% end %> -->

</div>

<div id = "footer">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WesAdmits20</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>